FROM node:lts AS build

WORKDIR /build

COPY ./src/ ./src/
COPY package.json package-lock.json tsconfig.json ./

RUN npm i
RUN npm run build


FROM node:lts

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /build/dist/ ./dist/
COPY ./proto/ ./proto/
COPY package.json package-lock.json ./

RUN npm i --omit=dev

CMD ["npm", "run", "start"]